#!/usr/bin/env node
// Build static/icons.svg — a local SVG sprite of the Lucide icons PlayClass uses.
// Source: lucide-react 1.34.0 (ISC) from the monorepo, the same set as components/ui/Icon.tsx,
// so a port maps 1:1. No CDN, no build step for the pages: they use
//   <svg class="ic" aria-hidden="true"><use href="/static/icons.svg#arrow-left"/></svg>
//
//   node scripts/build_icons.mjs [path/to/lucide-react/dist/esm/icons]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = process.argv[2] || path.resolve(here, '../../solveeducation/node_modules/lucide-react/dist/esm/icons');
const OUT = path.resolve(here, '../static/icons.svg');

// Only the icons the pages use (keep sorted). Add a name here, re-run, done.
const ICONS = [
  'arrow-down', 'arrow-left', 'arrow-right', 'arrow-up', 'book-open', 'calendar-clock', 'chart-column', 'check',
  'circle-check', 'circle-x', 'copy', 'crown', 'download', 'flag', 'graduation-cap', 'house', 'info', 'keyboard',
  'lightbulb', 'link', 'lock', 'log-out', 'maximize', 'moon', 'music', 'pause', 'pencil', 'play', 'plus',
  'rotate-ccw', 'school', 'settings', 'shuffle', 'skip-forward', 'square', 'sun', 'timer', 'trash-2', 'trophy',
  'user', 'users', 'volume-2', 'volume-x', 'x',
];

const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
function iconNode(name) {
  const src = fs.readFileSync(path.join(SRC, `${name}.mjs`), 'utf8');
  const m = src.match(/const __iconNode = (\[[\s\S]*?\]);\n/);
  if (!m) throw new Error(`no __iconNode in ${name}.mjs`);
  // The array literal is plain data ([tag, {attrs}] pairs); evaluate it without importing React.
  return Function(`"use strict"; return (${m[1]});`)();
}
const version = JSON.parse(fs.readFileSync(path.resolve(SRC, '../../../package.json'), 'utf8')).version;
const symbols = ICONS.map((name) => {
  const kids = iconNode(name).map(([tag, attrs]) => {
    const a = Object.entries(attrs).filter(([k]) => k !== 'key').map(([k, v]) => ` ${k}="${esc(v)}"`).join('');
    return `<${tag}${a}/>`;
  }).join('');
  return `  <symbol id="${name}" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${kids}</g></symbol>`;
});
const out = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- Lucide icons v${version} (ISC licence, https://lucide.dev). Generated by scripts/build_icons.mjs — do not edit by hand. -->
${symbols.join('\n')}
</svg>
`;
fs.writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${ICONS.length} icons (lucide-react ${version})`);
